//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRestaurante.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumo_comanda
    {
        public int idconsumo_comanda { get; set; }
        public Nullable<int> idmesa { get; set; }
        public Nullable<int> idcomanda { get; set; }
        public Nullable<int> itemproduto { get; set; }
        public Nullable<int> quantidade { get; set; }
    
        public virtual comanda comanda { get; set; }
        public virtual mesa mesa { get; set; }
        public virtual produto produto { get; set; }
    }
}
