//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRestaurante.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.consumo_comanda = new HashSet<consumo_comanda>();
        }
    
        public int idproduto { get; set; }
        public string nome { get; set; }
        public Nullable<double> preco { get; set; }
        public Nullable<int> idtipo { get; set; }
    
        public virtual ICollection<consumo_comanda> consumo_comanda { get; set; }
        public virtual tipo tipo { get; set; }
    }
}
