//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRestaurante.modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restaurantedbEntidades : DbContext
    {
        public restaurantedbEntidades()
            : base("name=restaurantedbEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comanda> comanda { get; set; }
        public DbSet<consumo_comanda> consumo_comanda { get; set; }
        public DbSet<mesa> mesa { get; set; }
        public DbSet<produto> produto { get; set; }
        public DbSet<tipo> tipo { get; set; }
    }
}
