//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjRestaurante.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo
    {
        public tipo()
        {
            this.produto = new HashSet<produto>();
        }
    
        public int idtipo { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<produto> produto { get; set; }
    }
}
